research_task:
  description: >
    Collect the latest news and information on {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list of dictionaries, each containing:
    - "title": The title of the news article.
    - "url": The URL where the article can be accessed.
    - "source": The name of the publication or source.
    - "published_date": The date and time the article was published in ISO 8601 format.
    - "snippet": A brief summary or snippet of the article content.
  agent: news_collector

fact_check_task:
  description: >
    Review the context you got and verify the accuracy of the information.
  expected_output: >
    A dictionary containing:
    - "verified_facts": A list of dictionaries, each with:
      - "claim": The statement or claim being verified.
      - "verification": A boolean indicating if the claim is verified.
      - "source": The source of the verification.
    - "unverified_claims": A list of claims that could not be verified.
    - "contradictions": A list of dictionaries, each with:
      - "claim": The statement or claim with contradictions.
      - "sources": A list of sources that contradict each other.
  agent: fact_checker

summary_task:
  description: >
    Create concise summaries of news articles and reports on {topic}
  expected_output: >
    A dictionary containing:
    - "title": The title of the summary.
    - "summary": A brief overview of the main findings or conclusions.
    - "key_points": A list of key points or highlights from the summary.
    - "sources": A list of URLs where the information was sourced.
  agent: summary_writer

trend_task:
  description: >
    Analyze trends and patterns in news data related to {topic}
  expected_output: >
    A dictionary containing:
    - "main_trend": A brief description of the primary trend identified.
    - "sub_trends": A list of sub-trends related to the main trend.
    - "sentiment_analysis": A dictionary with:
      - "overall_sentiment": A numerical representation of the overall sentiment.
      - "sentiment_breakdown": A dictionary with percentages of positive, neutral, and negative sentiments.
    - "key_entities": A list of dictionaries, each with:
      - "name": The name of the entity.
      - "type": The type of entity (e.g., Technology, Person).
      - "frequency": The frequency of the entity's mention.
    - "timeline": A list of dictionaries, each with:
      - "date": The date of the event in ISO 8601 format.
      - "event": A brief description of the event.
  agent: trend_analyzer
